(function(){
  const L=(id,category,title,level,description,objectives,sections,code,reference,mistakes,task,q,options,answer,explanation)=>({id,category,title,level,summary:description.split('.')[0]+'.',keywords:[title,...objectives].join(' '),description,objectives,points:objectives,sections:sections.map(([title,body])=>({title,body})),code,reference,mistakes,task,minutes:Math.max(12,sections.length*5),quiz:{question:q,options,answer,explanation}});
  window.APEX_CURRICULUM=window.APEX_CURRICULUM||{};
  window.APEX_CURRICULUM.python=[
    L('setup','Foundations','Setup, REPL, scripts, and execution','Beginner','Learn how Python code moves from a file or interactive prompt through the interpreter.',
      ['Install and identify a Python 3 interpreter','Use the REPL for experiments and a .py file for programs','Run modules with python -m','Read a basic traceback'],[
        ['Ways to run Python','The REPL executes one statement at a time and is ideal for quick experiments. A script is a saved .py file run with python path/to/file.py. python -m package.module runs a module through Python’s import system, which is important for packages and tools such as pip and venv.'],
        ['Interpreter and environment','python --version identifies the interpreter found on PATH. On systems with multiple installations, python3 or the Windows py launcher may be used. An editor does not execute Python by itself; it launches an interpreter selected for the project.'],
        ['Errors as information','A traceback lists the call path and ends with the exception type and message. Start with the final line, locate the referenced source line, reproduce the smallest failure, and inspect the values involved.']],
      `# hello.py\nname = input("Your name: ")\nprint(f"Hello, {name}!")\n\n# Terminal:\n# python hello.py\n# python -m pip --version`,
      [['REPL','Interactive read-evaluate-print loop'],['script','Saved Python source file'],['module','Importable Python file or package member'],['interpreter','Program that executes Python code'],['traceback','Stack of calls leading to an exception']],
      ['Editing with one interpreter and running with another','Naming a file after a standard module such as random.py','Ignoring the exception type at the end of a traceback'],
      'Create a script that asks for a name and study goal, prints a formatted message, and run it from a terminal.',
      'Which command runs an importable module through Python’s module system?',['python file.txt','python -m module','pip module','import module in the shell'],1,'python -m resolves and runs a module using the selected interpreter.'),

    L('syntax','Foundations','Syntax, indentation, comments, and names','Beginner','Master Python’s block structure, naming rules, statements, expressions, and comments.',
      ['Use four-space indentation consistently','Distinguish expressions from statements','Choose valid descriptive snake_case names','Write useful comments and docstrings'],[
        ['Blocks and indentation','A colon starts an indented suite after if, for, while, def, class, try, with, and match clauses. Indentation is syntax, not decoration. Four spaces are conventional; mixing tabs and spaces can cause errors or misleading structure.'],
        ['Names and expressions','Names begin with a letter or underscore, are case-sensitive, and cannot be keywords. An expression produces a value; a statement performs an operation such as assignment, import, or return. Long expressions can be continued naturally inside parentheses, brackets, or braces.'],
        ['Comments and documentation','A comment explains why, constraints, or non-obvious intent—not a direct translation of code. A docstring is the first string inside a module, class, or function and becomes runtime documentation available through help().']],
      `def final_price(subtotal: float, tax_rate: float) -> float:\n    """Return a subtotal including tax."""\n    # Tax rate is expressed as a decimal, for example 0.18.\n    return subtotal * (1 + tax_rate)\n\namount = final_price(100, 0.18)`,
      [['statement','Instruction such as assignment or return'],['expression','Code that evaluates to a value'],['suite','Indented block after a colon'],['docstring','Runtime documentation string'],['keyword','Reserved language word']],
      ['Mixing tabs and spaces','Using a keyword such as class as a variable name','Writing comments that merely repeat the next line'],
      'Fix a script containing inconsistent indentation, an invalid identifier, and an overlong expression; add one useful docstring.',
      'What defines a Python block?',['Curly braces','Indentation following a colon','Semicolons','Parentheses'],1,'Indented suites define the bodies of compound statements.'),

    L('variables-types','Foundations','Variables, objects, and core types','Beginner','Understand that names reference objects and learn the behavior of Python’s fundamental scalar types.',
      ['Use int, float, complex, bool, str, bytes, and None','Explain dynamic typing and object identity','Convert between compatible types','Use type checks without overusing them'],[
        ['Names reference objects','Assignment binds a name to an object; it does not declare a fixed storage type. Rebinding can make the name reference another type, though stable types make code easier to understand. id() exposes identity for learning, while is checks identity and == checks value equality.'],
        ['Numbers, truth, and absence','int has arbitrary precision; float uses binary floating-point; complex stores real and imaginary parts. bool is a subtype of int but represents truth values. None is the single object used to mean no value or not available and should be compared with is None.'],
        ['Conversion and introspection','int(), float(), str(), bool(), bytes(), and other constructors convert when a meaningful conversion exists. type(x) gives the exact type; isinstance(x, SomeType) includes subclasses and is usually better when a type check is genuinely required.']],
      `count = 12\nprice = 19.95\navailable = True\nresult = None\n\nprint(type(price))\nprint(isinstance(count, int))\nprint(result is None)`,
      [['int','Whole number of arbitrary size'],['float','Binary floating-point number'],['bool','True or False'],['None','Absence of a value'],['is','Identity comparison'],['==','Value comparison']],
      ['Using is to compare strings or numbers','Expecting decimal fractions to be exact floats','Using type checks instead of polymorphic behavior'],
      'Create a product record using suitable scalar values, convert text input to a number safely, and explain each chosen type.',
      'How should None normally be compared?',['value == 0','value is None','not type(value)','value == "None"'],1,'None is a singleton, so identity comparison is the clear conventional check.'),

    L('operators','Foundations','Operators, precedence, and numeric accuracy','Beginner','Calculate, compare, combine conditions, and choose accurate numeric representations.',
      ['Use arithmetic, comparison, identity, membership, and Boolean operators','Predict precedence and use parentheses for clarity','Apply short-circuit evaluation','Choose Decimal for exact decimal business arithmetic'],[
        ['Operator families','Arithmetic includes +, -, *, /, //, %, and **. Comparisons can chain: 0 <= score <= 100. in checks membership, is checks identity, and bitwise operators manipulate integer bits or specialized types. Assignment expressions := bind a value inside an expression but should improve—not reduce—clarity.'],
        ['Boolean evaluation','and returns the first falsy operand or last operand; or returns the first truthy operand; not returns a bool. This short-circuit behavior enables defaults and guarded work, but explicit conditional code can be clearer when operands are not booleans.'],
        ['Numeric accuracy','Binary floats cannot exactly represent many decimal fractions. Use math.isclose for tolerant comparisons and decimal.Decimal created from strings for exact base-10 money calculations. fractions.Fraction represents exact rational values.']],
      `from decimal import Decimal\nsubtotal = Decimal("19.95")\ntax = Decimal("0.18")\ntotal = subtotal * (1 + tax)\nprint(total.quantize(Decimal("0.01")))\n\nscore = 84\npassed = 0 <= score <= 100 and score >= 50`,
      [['//','Floor division'],['%','Remainder'],['**','Exponentiation'],['in','Membership'],['and / or','Short-circuit Boolean operators'],['Decimal','Exact base-10 arithmetic']],
      ['Comparing calculated floats with ==','Forgetting that // rounds down, including for negatives','Writing dense precedence-dependent expressions without parentheses'],
      'Build a bill calculator using Decimal, discounts, tax, and range checks; explain why float is not used.',
      'Which type is suitable for exact decimal currency calculations?',['float','complex','Decimal constructed from text','bool'],2,'Decimal from a string preserves the intended base-10 value.'),

    L('strings','Collections','Strings, Unicode, formatting, and text methods','Beginner','Work confidently with immutable Unicode text, indexing, slicing, searching, and formatting.',
      ['Create and combine strings with f-strings','Index and slice text safely','Normalize case and whitespace','Distinguish Unicode text from encoded bytes'],[
        ['Immutable sequences','str is an immutable sequence of Unicode code points. Indexing retrieves one character and slicing creates a new string. Negative indexes count from the end. Methods such as strip, replace, split, join, startswith, and casefold return new values.'],
        ['Formatting','f-strings embed expressions and support format specifications for width, alignment, precision, dates, and number grouping. repr-style debugging syntax such as f"{value=}" is useful during development. Do not build SQL or shell commands by interpolating untrusted values.'],
        ['Unicode and bytes','Human text is str. Encoded external data is bytes. encode converts text to bytes using a named encoding such as UTF-8; decode converts bytes back to text. casefold is stronger than lower for caseless comparison, and Unicode normalization may be needed when visually identical text has different code-point sequences.']],
      `from unicodedata import normalize\nname = "  Maya  "\nclean = normalize("NFC", name.strip())\nscore = 12345.678\nprint(f"{clean}: {score:,.1f} XP")\nwords = "html,python,dbms".split(",")\nprint(" | ".join(words))`,
      [['strip','Remove surrounding whitespace'],['split','Text to list'],['join','Iterable of text to one string'],['casefold','Aggressive caseless comparison'],['encode / decode','Convert between str and bytes'],['NFC','Common Unicode normalization form']],
      ['Repeatedly concatenating huge strings in a loop','Confusing bytes with text','Using lower when international caseless matching requires casefold'],
      'Write a function that normalizes a name, validates a simple slug, and formats a report line with aligned and grouped values.',
      'What does str.join expect?',['One number','An iterable of strings','A file object only','Two dictionaries'],1,'join combines an iterable whose elements are strings.'),

    L('lists-tuples','Collections','Lists, tuples, slicing, and unpacking','Beginner','Choose mutable and immutable sequences and manipulate them without accidental aliasing.',
      ['Create, index, slice, and copy sequences','Use list mutation methods deliberately','Unpack fixed and variable-length sequences','Explain shallow copies and shared nested objects'],[
        ['Lists and mutation','Lists are ordered mutable references. append adds one object, extend adds every item from an iterable, insert adds at a position, pop removes and returns, and remove deletes the first equal value. sort mutates and returns None; sorted returns a new list from any iterable.'],
        ['Tuples and records','Tuples are immutable sequences and can be dictionary keys when all members are hashable. Parentheses do not create a tuple—the comma does. Tuples suit fixed heterogeneous records and multi-value returns, though dataclasses or named tuples add clearer field names.'],
        ['Slicing, copying, unpacking','sequence[start:stop:step] returns a slice. list[:] and list.copy() make shallow copies, so nested mutable objects remain shared. Unpacking assigns positions to names; starred targets collect remaining items.']],
      `topics = ["HTML", "Python", "DBMS"]\ntopics.append("Testing")\nfirst, *middle, last = topics\ncopy = topics.copy()\nranked = sorted(topics, key=str.casefold)\npoint = (12, 8)`,
      [['append(x)','Add one item'],['extend(items)','Add items from an iterable'],['sort()','Sort a list in place'],['sorted(items)','Return a sorted list'],['a, *rest','Extended unpacking'],['shallow copy','New outer container, shared nested objects']],
      ['Assigning b = a and expecting a copy','Using append when extend is intended','Writing result = values.sort() and receiving None'],
      'Implement a lesson queue that adds, removes, slices, sorts, copies, and unpacks items; demonstrate one shallow-copy surprise.',
      'What does list.sort() return?',['The sorted list','None','A tuple','An iterator'],1,'sort mutates the existing list and returns None.'),

    L('dicts-sets','Collections','Dictionaries, sets, and hashability','Intermediate','Model keyed records, unique collections, and fast membership checks.',
      ['Create, update, merge, and iterate dictionaries','Use get, setdefault, and comprehensions appropriately','Perform set algebra','Explain hashability requirements'],[
        ['Dictionary behavior','dict preserves insertion order and maps unique hashable keys to values. Access with [] when absence is an error and get when a default is expected. items yields key-value pairs. The | operator merges dictionaries, with right-side values winning on duplicate keys.'],
        ['Sets and algebra','set stores unique hashable values. union |, intersection &, difference -, and symmetric difference ^ express collection relationships directly. frozenset is immutable and hashable. Sets are unordered for semantic purposes even if an observed iteration order appears stable.'],
        ['Hashability','Hashable objects have a stable hash and equality behavior and can be keys or set members. Immutable built-ins such as strings, numbers, and suitable tuples are hashable; lists, dicts, and sets are not. Custom mutable objects need careful equality and hashing design.']],
      `student = {"name": "Maya", "xp": 850}\nstudent["track"] = "Python"\nfor key, value in student.items():\n    print(key, value)\nrequired = {"html", "python", "dbms"}\ncompleted = {"html", "python"}\nprint(required - completed)`,
      [['dict.get','Value or default without insertion'],['setdefault','Get or insert a default'],['items','Key-value view'],['union |','Members from either set'],['intersection &','Members shared by both'],['hashable','Stable hash and equality']],
      ['Catching KeyError by using get everywhere and hiding real mistakes','Depending on set order','Trying to use a list as a dictionary key'],
      'Build a progress tracker with a dictionary per learner and set operations for completed, required, and remaining modules.',
      'Which collection directly models unique unordered membership?',['list','tuple','set','str'],2,'A set stores unique hashable members and supports set algebra.'),

    L('control-flow','Control flow','Conditions, pattern matching, and truthiness','Intermediate','Express decisions clearly with if, conditional expressions, and structural pattern matching.',
      ['Write ordered if, elif, and else branches','Understand truthy and falsy values','Use conditional expressions sparingly','Apply match and guards to structured data'],[
        ['Conditional branches','Conditions are tested top to bottom and only the first matching branch runs. Put specific cases before general cases. Empty containers, zero, None, and False are falsy; most other objects are truthy, though custom classes can define truth testing.'],
        ['Conditional expressions','x if condition else y is an expression for a small two-way value choice. Nested conditional expressions quickly become unreadable and should become ordinary branches. Use is None when absence differs from other falsy values such as 0 or an empty string.'],
        ['Structural pattern matching','match compares structure, not only equality. Literal, sequence, mapping, class, OR, wildcard, capture, and guarded patterns can unpack validated shapes. A bare name captures anything, so cases must be ordered carefully.']],
      `def route(command):\n    match command:\n        case {"action": "open", "topic": str(topic)}:\n            return f"Opening {topic}"\n        case {"action": "score", "value": int(value)} if value >= 0:\n            return f"Score: {value}"\n        case _:\n            return "Unknown command"`,
      [['truthy','Treated as true in a condition'],['elif','Additional exclusive branch'],['conditional expression','value_if_true if condition else value_if_false'],['match','Structural pattern selection'],['guard','Additional if condition on a case']],
      ['Testing general conditions before specific ones','Using if value when zero is a valid distinct value','Expecting match to fall through like a C switch'],
      'Write a command router with mapping patterns, type patterns, guards, and a safe default case.',
      'Does Python match fall through to later cases after one succeeds?',['Yes','No','Only for strings','Only with break'],1,'The first matching case runs; there is no implicit fall-through.'),

    L('loops','Control flow','Loops, iteration tools, and loop control','Beginner','Iterate directly, track positions, combine iterables, and stop or skip work precisely.',
      ['Choose for versus while','Use range, enumerate, zip, reversed, and sorted','Apply break, continue, and loop else','Avoid mutation hazards while iterating'],[
        ['Iterable-first loops','for asks an iterable for values; it is not limited to numeric counters. range generates arithmetic integer sequences lazily. enumerate yields index-value pairs. zip pairs corresponding values and stops at the shortest iterable unless strict=True requests equal lengths.'],
        ['Control statements','continue skips to the next iteration; break exits the nearest loop. A loop else block runs only when the loop finishes without break, which can express a search with a not-found result. return exits the entire function, not just the loop.'],
        ['Safe iteration','Mutating the size of a list or dictionary during iteration can skip work or raise an error. Iterate over a copy, build a new collection, or collect changes for later. A while loop must update the state used by its condition and should have a clear termination argument.']],
      `topics = ["HTML", "Python", "DBMS"]\nfor number, topic in enumerate(topics, start=1):\n    print(number, topic)\n\nneedle = "Python"\nfor topic in topics:\n    if topic == needle:\n        print("Found")\n        break\nelse:\n    print("Not found")`,
      [['range','Lazy integer sequence'],['enumerate','Index-value pairs'],['zip','Parallel iteration'],['break','Exit nearest loop'],['continue','Skip current iteration'],['loop else','Runs when no break occurred']],
      ['Using range(len(items)) when direct iteration is clearer','Forgetting that zip normally truncates to the shortest input','Changing dictionary size while iterating over it'],
      'Process two aligned lists with zip(strict=True), skip invalid rows, number accepted rows, and report whether a requested id was found.',
      'When does a loop else block run?',['After every break','When the loop finishes without break','Only when the iterable is empty','Before the first iteration'],1,'Loop else represents normal exhaustion rather than early break.'),

    L('functions','Functions','Functions, parameters, and return values','Intermediate','Design focused reusable operations with clear interfaces and predictable values.',
      ['Define functions with docstrings and return values','Use positional, keyword, default, positional-only, and keyword-only parameters','Accept variadic arguments intentionally','Avoid mutable default arguments'],[
        ['Function contract','A good function has one clear responsibility, a meaningful name, explicit inputs, a documented result, and limited side effects. return sends one object; multiple comma-separated values are a tuple. Reaching the end returns None.'],
        ['Parameter kinds','Parameters before / are positional-only; parameters after * are keyword-only. Ordinary parameters accept either form. *args collects extra positional arguments in a tuple and **kwargs collects extra keyword arguments in a dict. These features support clear APIs but should not hide an undefined interface.'],
        ['Defaults and calls','Default expressions are evaluated once when def executes. A mutable default therefore persists across calls; use None and create a new object inside. Keyword calls improve readability, but callers must follow positional arguments before keyword arguments and cannot bind one parameter twice.']],
      `def record_score(name, score, /, *, tags=None):\n    """Return a normalized score record."""\n    if not 0 <= score <= 100:\n        raise ValueError("score must be 0 through 100")\n    return {"name": name.strip(), "score": score, "tags": list(tags or [])}\n\nrecord = record_score(" Maya ", 92, tags=["python"])`,
      [['/','Parameters before it are positional-only'],['*','Parameters after it are keyword-only'],['*args','Extra positional arguments'],['**kwargs','Extra keyword arguments'],['return','End function and provide a value']],
      ['Using a list or dict as a default value','Printing a result instead of returning reusable data','Creating functions with many unrelated responsibilities'],
      'Design a grade function with validation, keyword-only configuration, a safe optional collection, a docstring, and tests.',
      'When is a default argument expression evaluated?',['Every call','When def executes','At program exit','Only after an exception'],1,'Defaults are created once at function definition time.'),

    L('scope-closures','Functions','Scope, closures, and decorators','Advanced','Understand name resolution, retain function state, and wrap behavior safely.',
      ['Explain LEGB name lookup','Use nonlocal and global sparingly','Create closures that retain state','Write decorators with functools.wraps'],[
        ['LEGB resolution','Python searches Local, Enclosing, Global, then Builtins. Assignment makes a name local unless global or nonlocal declares otherwise. Reading a would-be local before assignment raises UnboundLocalError. Small explicit interfaces are safer than broad global state.'],
        ['Closures','A nested function closes over names from its enclosing function. nonlocal allows rebinding an enclosing local and is useful for small stateful helpers. Closures can implement factories and configuration without a class, but hidden mutable state can complicate tests.'],
        ['Decorators','A decorator receives a function or class and returns a replacement. Function wrappers should accept suitable arguments, return the wrapped result, and use functools.wraps to preserve name, docstring, and introspection metadata.']],
      `from functools import wraps\n\ndef count_calls(function):\n    calls = 0\n    @wraps(function)\n    def wrapper(*args, **kwargs):\n        nonlocal calls\n        calls += 1\n        print(f"call {calls}")\n        return function(*args, **kwargs)\n    return wrapper\n\n@count_calls\ndef greet(name): return f"Hello, {name}"`,
      [['LEGB','Local, Enclosing, Global, Builtins'],['nonlocal','Rebind enclosing function name'],['global','Rebind module-level name'],['closure','Function retaining enclosing values'],['decorator','Callable transforming a callable or class'],['wraps','Preserves wrapped function metadata']],
      ['Using global for routine data flow','Writing a decorator that discards the return value','Forgetting wraps and breaking introspection'],
      'Create a timing or call-count decorator that preserves metadata, accepts arbitrary arguments, and returns the original result.',
      'Which declaration rebinds a name in the nearest enclosing function?',['global','nonlocal','import','yield'],1,'nonlocal refers to a binding in an enclosing function scope.'),

    L('comprehensions-generators','Iteration','Comprehensions, iterators, and generators','Intermediate','Build collections concisely and stream values without storing everything.',
      ['Write readable list, set, and dictionary comprehensions','Explain iterable, iterator, and StopIteration','Create generator functions and expressions','Choose lazy versus eager processing'],[
        ['Comprehensions','A comprehension combines mapping and optional filtering. Keep it to one clear expression and at most a simple nested loop; complex branching belongs in a named function and normal loop. Dictionary comprehensions produce key-value pairs, and set comprehensions remove duplicates.'],
        ['Iterator protocol','An iterable returns an iterator from iter(). An iterator returns itself and produces values from next() until StopIteration. for handles this protocol automatically. Many iterators are single-use streams rather than reusable containers.'],
        ['Generators','A function containing yield returns a generator iterator. State is suspended between yielded values. yield from delegates to another iterable. Generator expressions use parentheses and support lazy pipelines, which save memory but defer errors and cannot be rewound.']],
      `def read_batches(rows, size):\n    batch = []\n    for row in rows:\n        batch.append(row)\n        if len(batch) == size:\n            yield batch\n            batch = []\n    if batch:\n        yield batch\n\nsquares = {n: n * n for n in range(6) if n % 2 == 0}`,
      [['iterable','Object that can create an iterator'],['iterator','Single-use value stream'],['yield','Produce and suspend'],['yield from','Delegate iteration'],['generator expression','Lazy comprehension-like expression']],
      ['Using a dense comprehension with several side effects','Expecting an exhausted generator to restart','Converting a huge generator to list and losing the memory benefit'],
      'Write a generator pipeline that reads records, filters invalid entries, transforms valid entries, and yields fixed-size batches.',
      'What happens when a generator reaches return or the function end?',['It restarts','It raises StopIteration to its consumer','It becomes a list','It deletes yielded values'],1,'Generator completion is signaled through StopIteration.'),

    L('exceptions','Reliability','Exceptions, cleanup, and custom errors','Intermediate','Handle expected failures at the right layer while preserving debugging information.',
      ['Catch specific exceptions','Use try, except, else, and finally correctly','Raise and chain meaningful errors','Create small domain-specific exception classes'],[
        ['Exception flow','Put only the operation that may fail in try. Catch the narrow exceptions you can resolve or translate. else runs when no exception occurred and keeps successful work out of the protected block. finally runs during success, failure, return, or break and is for unavoidable cleanup.'],
        ['Raising and chaining','raise ValueError("...") signals invalid data. raise by itself re-raises the active exception with its traceback. raise DomainError(...) from error records an explicit cause; from None suppresses a noisy implementation cause when appropriate. Error messages should identify the failed rule and relevant safe context.'],
        ['Boundary design','Low-level code should not silently replace every failure with None. Translate exceptions at abstraction boundaries and let callers decide policy. Never catch BaseException for ordinary recovery because it includes shutdown signals such as KeyboardInterrupt and SystemExit.']],
      `class ScoreError(ValueError):\n    pass\n\ndef parse_score(text):\n    try:\n        score = int(text)\n    except ValueError as error:\n        raise ScoreError(f"not a whole-number score: {text!r}") from error\n    if not 0 <= score <= 100:\n        raise ScoreError("score must be 0 through 100")\n    return score`,
      [['try','Protected operation'],['except','Handle matching exception'],['else','Runs after successful try'],['finally','Cleanup path'],['raise from','Explicit exception chaining']],
      ['Catching Exception around an entire program and continuing','Returning None for every failure without documentation','Losing the original cause when translating errors'],
      'Create a parser that raises a custom validation error, chains conversion failures, and lets file-access failures remain distinct.',
      'Which block runs only when try completed without an exception?',['except','else','finally','raise'],1,'try-else separates success-only work from exception handling.'),

    L('files-paths','Data and I/O','Files, paths, encodings, CSV, and JSON','Intermediate','Read and write common data safely with explicit encodings, context managers, and path objects.',
      ['Use pathlib for portable paths','Open text with explicit encoding and context management','Process files incrementally','Read and write JSON and CSV with suitable types'],[
        ['Paths and files','pathlib.Path composes paths, tests metadata, iterates directories, and reads or writes small files. with open(...) closes resources even after failure. Use encoding="utf-8" for text you control and newline="" when the csv module manages line endings.'],
        ['Streaming and atomicity','Iterating a text file reads incrementally. For important replacement writes, write a temporary file in the same directory, flush as needed, then replace the destination atomically. Validate paths and never let untrusted input escape an allowed directory.'],
        ['JSON and CSV','JSON supports objects, arrays, strings, numbers, booleans, and null, not arbitrary Python objects. json.load/dump work with files; loads/dumps work with strings. csv.DictReader and DictWriter map rows by header names but values arrive as strings and need validation.']],
      `import json\nfrom pathlib import Path\npath = Path("data") / "progress.json"\npath.parent.mkdir(exist_ok=True)\nprogress = {"html": 12, "python": 9, "dbms": 7}\nwith path.open("w", encoding="utf-8") as file:\n    json.dump(progress, file, ensure_ascii=False, indent=2)\nwith path.open(encoding="utf-8") as file:\n    restored = json.load(file)`,
      [['Path','Object-oriented filesystem path'],['with','Context-managed lifetime'],['encoding','Text-to-byte mapping'],['json.load','JSON file to Python'],['json.dump','Python data to JSON file'],['DictReader','CSV rows as dictionaries']],
      ['Using a platform-specific path separator in string concatenation','Opening controlled text without an explicit encoding','Assuming JSON can serialize datetime or custom classes automatically'],
      'Import learner records from CSV, validate and convert fields, report row errors, and atomically write valid records to formatted JSON.',
      'What type are ordinary CSV field values when read?',['Always int','Strings','Bytes only','Sets'],1,'CSV is text; application code must parse and validate field types.'),

    L('modules-packages','Projects','Modules, packages, imports, and environments','Intermediate','Organize code, resolve imports predictably, and isolate project dependencies.',
      ['Build modules and packages','Use absolute and relative imports appropriately','Protect script entry points','Create virtual environments and record dependencies'],[
        ['Modules and packages','A module is an importable unit, commonly one .py file. A package groups modules and usually contains __init__.py, though namespace packages can omit it. Imports execute a module once per interpreter process and cache it in sys.modules. Avoid meaningful side effects at import time.'],
        ['Import design','Prefer explicit imports and avoid from module import *. Absolute imports show the package path; explicit relative imports can connect internal sibling modules. Circular imports often reveal misplaced shared responsibilities and should be fixed by redesign rather than import tricks.'],
        ['Environments and entry points','python -m venv .venv creates an isolated environment. Use python -m pip so pip belongs to the selected interpreter. Record direct dependencies and reproducible versions using project metadata or an appropriate lock workflow. if __name__ == "__main__" protects code that should run only as a script.']],
      `# apex/report.py\ndef build_report(): return "ready"\n\n# apex/__main__.py\nfrom .report import build_report\n\ndef main(): print(build_report())\n\nif __name__ == "__main__":\n    main()\n\n# Run: python -m apex`,
      [['module','Importable Python unit'],['package','Namespace containing modules'],['sys.modules','Import cache'],['venv','Isolated Python environment'],['__main__','Script execution context'],['pyproject.toml','Modern project metadata']],
      ['Running pip from a different interpreter than python','Creating circular imports between feature modules','Doing network or database work during import'],
      'Split a small program into package modules, add a python -m entry point, create a venv, and document its direct dependency.',
      'Why use python -m pip?',['It is shorter','It ties pip to the chosen interpreter','It installs globally','It disables environments'],1,'The selected Python interpreter runs its corresponding pip module.'),

    L('oop','Object-oriented Python','Classes, instances, properties, and dataclasses','Intermediate','Model related state and behavior while keeping invariants explicit.',
      ['Define instance and class attributes','Use methods, properties, and class methods','Create data-focused classes with dataclasses','Prefer simple functions when objects add no value'],[
        ['Object model','A class creates instances. __init__ initializes an already created instance; self is the instance passed to methods. Instance attributes belong to each object, while class attributes are shared unless shadowed. Methods are functions that become bound when accessed through an instance.'],
        ['Properties and constructors','A property provides attribute syntax backed by methods and is useful for a computed value or invariant-preserving change. classmethod receives cls and commonly implements alternative constructors. staticmethod is a namespaced function and is less often necessary.'],
        ['Dataclasses','@dataclass generates initialization, representation, comparison, and other methods for data-oriented classes. Use field(default_factory=list) for mutable defaults. frozen=True prevents normal reassignment but does not deeply freeze nested objects.']],
      `from dataclasses import dataclass, field\n\n@dataclass(slots=True)\nclass Learner:\n    name: str\n    completed: set[str] = field(default_factory=set)\n\n    @property\n    def level(self) -> int:\n        return len(self.completed) // 5 + 1\n\n    def complete(self, topic: str) -> None:\n        self.completed.add(topic)`,
      [['instance attribute','Per-object state'],['class attribute','State on the class'],['property','Managed or computed attribute'],['classmethod','Method receiving cls'],['dataclass','Generated data-class methods'],['default_factory','Fresh mutable default per instance']],
      ['Placing a mutable list as a class attribute by accident','Writing getters and setters that add no behavior','Turning every dictionary into a class without a useful invariant'],
      'Create a dataclass for a course with validated enrollment, a computed seats_remaining property, and a safe collection default.',
      'How should a dataclass create a fresh list for every instance?',['default=[]','field(default_factory=list)','list as a class variable','property(list)'],1,'default_factory runs for each new instance.'),

    L('inheritance-protocols','Object-oriented Python','Inheritance, composition, protocols, and special methods','Advanced','Reuse behavior without brittle hierarchies and integrate custom objects with Python syntax.',
      ['Choose composition versus inheritance','Use super cooperatively','Define structural interfaces with protocols','Implement selected special methods consistently'],[
        ['Inheritance and composition','Inheritance models a true substitutable is-a relationship. Composition gives an object collaborators and is easier to change independently. Deep hierarchies create fragile coupling. Multiple inheritance works best with cooperative super calls and mixins that have focused behavior.'],
        ['Protocols and duck typing','Python code often depends on behavior rather than concrete classes. typing.Protocol documents structural requirements for static checkers: any object with the required methods satisfies the protocol. Abstract base classes provide runtime relationships and shared implementation when needed.'],
        ['Special methods','__repr__ gives a developer representation; __str__ gives user text; __len__, __iter__, __contains__, comparisons, arithmetic, and context methods integrate with syntax. Return NotImplemented for unsupported binary comparisons so Python can try reflected behavior. Keep equality and hashing consistent.']],
      `from typing import Protocol\n\nclass Saveable(Protocol):\n    def save(self) -> None: ...\n\ndef persist(item: Saveable) -> None:\n    item.save()\n\nclass Course:\n    def __init__(self, title): self.title = title\n    def __repr__(self): return f"Course({self.title!r})"`,
      [['composition','Object owns collaborators'],['inheritance','Subtype extends base behavior'],['Protocol','Structural static interface'],['super','Cooperative next implementation'],['dunder method','Special syntax integration hook'],['NotImplemented','Unsupported binary operation signal']],
      ['Using inheritance only to share a few utility methods','Calling a specific base class instead of cooperative super in multiple inheritance','Defining __eq__ but leaving an inconsistent hash'],
      'Refactor a payment class hierarchy into protocols and composition; add useful repr and equality behavior.',
      'Which relationship is usually more flexible for swapping collaborators?',['Deep inheritance','Composition','Global state','Monkey patching'],1,'Composition keeps collaborators replaceable without requiring a subtype hierarchy.'),

    L('typing','Quality','Type hints, generics, and static checking','Advanced','Document interfaces and catch mismatches without changing Python’s runtime model.',
      ['Annotate values, parameters, returns, and collections','Use unions, narrowing, type aliases, and generics','Define TypedDict and Protocol interfaces','Understand that hints are not automatic runtime validation'],[
        ['Core annotations','Built-in collection generics use list[str], dict[str, int], and tuple[int, ...]. X | None expresses an optional value. Type aliases name complex shapes. Type checkers use control flow and isinstance to narrow unions. Annotate public boundaries first.'],
        ['Structured data and generics','TypedDict describes dictionary keys for static analysis; dataclasses create runtime objects. TypeVar and generic classes or functions preserve relationships between input and output types. Protocol captures required behavior without inheritance.'],
        ['Limits and workflow','Annotations are available at runtime but Python does not enforce them automatically. Use validation libraries or explicit checks at untrusted boundaries. Run a checker in development and CI, but do not add casts merely to silence a real design problem.']],
      `from typing import Iterable, TypeVar, TypedDict\nT = TypeVar("T")\n\nclass TopicRow(TypedDict):\n    id: str\n    title: str\n\ndef first(items: Iterable[T]) -> T | None:\n    return next(iter(items), None)`,
      [['X | None','Value may be X or None'],['TypedDict','Typed dictionary shape'],['TypeVar','Related generic type variable'],['Protocol','Structural interface'],['cast','Static assertion, no runtime conversion']],
      ['Believing annotations validate network input','Annotating every local before useful interfaces','Using Any broadly and losing checker value'],
      'Add useful annotations to a data-processing module, define one TypedDict and one generic helper, then run a static checker.',
      'Do ordinary type hints reject a wrong value at runtime by themselves?',['Yes','No','Only for lists','Only in functions'],1,'Hints guide tools and readers; explicit validation is still required.'),

    L('context-decorators','Advanced language','Context managers and resource lifetimes','Advanced','Guarantee setup and cleanup around files, locks, transactions, and temporary state.',
      ['Use with for deterministic cleanup','Implement __enter__ and __exit__','Create generator context managers','Understand exception handling inside a context manager'],[
        ['Context protocol','with calls __enter__, binds its result after as, and always calls __exit__ with exception information. Returning a truthy value from __exit__ suppresses the exception and should be deliberate. Contexts can manage any paired acquire-release behavior.'],
        ['contextlib helpers','@contextmanager turns a generator with one yield into a context manager: code before yield enters, code after yield exits. ExitStack manages a dynamic number of contexts. closing adapts objects with close, suppress handles very narrow acceptable exceptions, and nullcontext supplies an optional no-op context.'],
        ['Transactional thinking','A context manager can begin a transaction, commit after success, and roll back after failure. Cleanup code itself must be reliable and should not obscure the original exception. Keep resource ownership clear: the code that acquires a resource should normally control its lifetime.']],
      `from contextlib import contextmanager\n\n@contextmanager\ndef transaction(connection):\n    try:\n        yield connection\n    except Exception:\n        connection.rollback()\n        raise\n    else:\n        connection.commit()\n\nwith transaction(db) as connection:\n    connection.execute("UPDATE learners SET xp = xp + ?", (100,))`,
      [['__enter__','Acquire and return context value'],['__exit__','Release with exception information'],['contextmanager','Generator-based context'],['ExitStack','Dynamic context collection'],['nullcontext','Optional no-op context']],
      ['Catching and suppressing unexpected errors in __exit__','Yielding more than once from a contextmanager generator','Opening a resource far from the code responsible for closing it'],
      'Create a temporary-settings context manager that restores the original state on success and failure; test both paths.',
      'What must a @contextmanager generator do?',['Yield exactly once','Return a list','Catch every exception','Use a class'],0,'One yield separates entry logic from exit logic.'),

    L('regex-datetime','Standard library','Regular expressions, dates, and time zones','Intermediate','Apply two commonly misused standard-library areas with validation and timezone awareness.',
      ['Write readable regular expressions and choose fullmatch, search, or finditer','Use raw strings and named groups','Create timezone-aware datetimes','Parse and format ISO-style timestamps'],[
        ['Regular-expression strategy','Use ordinary string methods for simple prefix, suffix, split, or replacement tasks. re.fullmatch validates an entire string, search finds anywhere, and finditer streams match objects. Raw string literals reduce backslash confusion. Named groups document extracted values.'],
        ['Dates and durations','date represents a calendar date, time a clock time, datetime both, and timedelta a duration. Naive datetimes lack a timezone interpretation; aware datetimes include tzinfo. Store or exchange instants in UTC and convert to a user’s zone for display.'],
        ['Time zones and parsing','zoneinfo.ZoneInfo uses IANA zone rules including daylight-saving transitions. datetime.fromisoformat parses many ISO forms. strptime handles a specified external format and strftime formats output. Do not treat timezone abbreviations or fixed offsets as full geographic zone rules.']],
      `import re\nfrom datetime import datetime, timezone\nfrom zoneinfo import ZoneInfo\n\nslug = "python-functions"\nif not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", slug):\n    raise ValueError("invalid slug")\nnow_utc = datetime.now(timezone.utc)\nprint(now_utc.astimezone(ZoneInfo("Asia/Kolkata")).isoformat())`,
      [['fullmatch','Entire text must match'],['search','Find first match anywhere'],['named group','Captured value with a name'],['aware datetime','Datetime with timezone'],['ZoneInfo','IANA timezone rules'],['timedelta','Duration']],
      ['Using regex for a task that split or startswith solves clearly','Comparing naive and aware datetimes','Using a fixed offset as if it handled daylight-saving rules'],
      'Validate course slugs, extract named fields from a log line, and display one UTC instant in two IANA time zones.',
      'Which object contains regional daylight-saving rules?',['timedelta','ZoneInfo','date','re.Pattern'],1,'ZoneInfo loads IANA timezone behavior for a named region.'),

    L('testing','Quality','Testing with unittest/pytest concepts','Essential','Design testable code and verify normal, boundary, and failure behavior.',
      ['Separate pure logic from I/O','Arrange, act, and assert clearly','Test boundaries and expected exceptions','Use fixtures and mocks only at real boundaries'],[
        ['Test design','A test should have one understandable reason to fail. Arrange inputs and dependencies, act once, and assert observable behavior. Test public outcomes instead of private implementation steps so refactoring remains possible.'],
        ['Cases and organization','Cover representative normal cases, boundaries, empty values, invalid values, and important exceptions. Parameterization expresses the same rule across inputs. Fixtures create reusable setup with controlled lifetime. Integration tests verify components together; unit tests isolate focused logic.'],
        ['Mocks and reliability','Mock slow or nondeterministic boundaries such as network, clock, random generator, or external service—not every internal function. Assert important interactions without copying implementation. Tests must be deterministic, independent, fast enough for feedback, and readable as specifications.']],
      `import pytest\n\n@pytest.mark.parametrize("score,grade", [(90,"A"),(75,"B"),(0,"F")])\ndef test_grade_boundaries(score, grade):\n    assert calculate_grade(score) == grade\n\ndef test_grade_rejects_out_of_range():\n    with pytest.raises(ValueError, match="0 through 100"):\n        calculate_grade(101)`,
      [['unit test','Focused component test'],['integration test','Components working together'],['fixture','Reusable test setup'],['parameterization','Same rule over many cases'],['mock','Controlled boundary substitute']],
      ['Testing only the happy path','Mocking the function under test','Sharing mutable state between tests'],
      'Write a test matrix for a score parser covering normal, boundary, malformed, missing, and out-of-range input.',
      'What should a unit test mainly assert?',['Private line execution','Observable behavior','Exact local variable names','Comment wording'],1,'Behavior-focused tests survive legitimate internal refactoring.'),

    L('debug-logging','Quality','Debugging, logging, and observability','Intermediate','Move from symptoms to causes and leave useful runtime evidence.',
      ['Read full tracebacks and reproduce failures','Use breakpoint and a debugger','Configure structured, leveled logging','Avoid logging secrets and duplicate messages'],[
        ['Debugging process','Make the failure repeatable, reduce it to the smallest case, state a hypothesis, inspect relevant values, and change one factor at a time. breakpoint() enters the configured debugger. Examine the call stack and step over, into, or out rather than scattering permanent prints.'],
        ['Logging levels','DEBUG gives development detail, INFO records normal milestones, WARNING signals recoverable concern, ERROR records failed operations, and CRITICAL marks severe service failure. Module loggers created with logging.getLogger(__name__) allow centralized configuration.'],
        ['Useful context','Log stable event text plus identifiers, duration, counts, and exception information. logger.exception inside except includes the traceback. Redact passwords, tokens, personal data, and large payloads. Libraries should not configure the application’s global handlers.']],
      `import logging\nlogger = logging.getLogger(__name__)\n\ndef import_rows(rows):\n    logger.info("import_started rows=%d", len(rows))\n    try:\n        result = validate(rows)\n    except ValueError:\n        logger.exception("import_validation_failed")\n        raise\n    logger.info("import_completed accepted=%d", len(result))\n    return result`,
      [['breakpoint()','Enter debugger'],['logger.exception','Error plus active traceback'],['DEBUG','Detailed diagnostic events'],['INFO','Normal lifecycle event'],['handler','Log destination'],['formatter','Log representation']],
      ['Logging secrets or complete sensitive requests','Using ERROR for ordinary expected user mistakes','Adding handlers inside reusable library modules'],
      'Debug a failing parser with breakpoint, then add safe start, failure, and completion logs with useful context.',
      'Which logging call includes the active traceback inside except?',['logger.info','logger.exception','print','logger.debug without exc_info'],1,'logger.exception records an error and current exception traceback.'),

    L('async-concurrency','Concurrency','Asyncio, threads, processes, and cancellation','Advanced','Choose a concurrency model and coordinate work without blocking or corrupting state.',
      ['Use async and await for many I/O waits','Run coroutines as tasks and collect results','Distinguish threads, processes, and asyncio','Handle cancellation, timeouts, and shared state'],[
        ['Asyncio model','A coroutine cooperatively yields control at await points. asyncio.create_task schedules concurrent coroutine progress, gather collects results, TaskGroup provides structured task lifetime, and queues or semaphores bound work. Blocking CPU or file calls freeze the event loop unless moved to a thread or process.'],
        ['Threads and processes','Threads share memory and suit blocking I/O or libraries without async APIs; locks protect shared mutable state. The GIL limits parallel execution of ordinary Python bytecode in common CPython builds. Processes have separate memory and suit CPU-bound work but require serialization and higher startup cost.'],
        ['Cancellation and timeouts','Cancellation is a normal control path. Use finally or contexts to release resources and usually re-raise CancelledError. timeout bounds waiting. Structured concurrency ensures child tasks finish or cancel before leaving their scope, preventing orphan background work.']],
      `import asyncio\n\nasync def fetch_topic(client, topic_id):\n    async with asyncio.timeout(5):\n        return await client.get(f"/topics/{topic_id}")\n\nasync def load_all(client, ids):\n    async with asyncio.TaskGroup() as group:\n        tasks = [group.create_task(fetch_topic(client, i)) for i in ids]\n    return [task.result() for task in tasks]`,
      [['coroutine','Awaitable async function execution'],['task','Scheduled coroutine'],['TaskGroup','Structured task lifetime'],['thread','Shared-memory concurrent worker'],['process','Separate-memory parallel worker'],['cancellation','Request for cooperative termination']],
      ['Calling time.sleep inside async code','Creating tasks and losing their references or errors','Holding a thread lock while awaiting'],
      'Build a bounded concurrent fetcher with a semaphore, per-request timeout, cancellation-safe cleanup, and collected error reporting.',
      'What is usually best for CPU-bound pure Python work?',['More asyncio tasks','A process pool','time.sleep','One global lock'],1,'Processes can execute CPU work in parallel with separate interpreters.'),

    L('database-api','Applications','SQLite, DB-API, and safe SQL','Intermediate','Store relational data from Python using transactions and parameterized queries.',
      ['Connect to SQLite with context management','Create tables and execute CRUD statements','Bind values with parameters','Control transactions and row access'],[
        ['DB-API shape','Python database drivers commonly expose connections and cursors following DB-API conventions. sqlite3 is included in the standard library. Connections manage transactions; execute sends SQL with bound parameters; rows can be tuples or mapped through a row factory.'],
        ['Parameters and safety','Never concatenate untrusted values into SQL. Placeholder style depends on the driver; sqlite3 uses ?. Parameters bind data, not table or column identifiers. Dynamic identifiers need a strict allowlist or driver-specific identifier composition.'],
        ['Transactions and lifetime','A connection context commits after success and rolls back after an exception, but closing behavior depends on the object and version, so own it explicitly. Keep transactions short, define constraints in the schema, and handle expected integrity errors.']],
      `import sqlite3\n\nwith sqlite3.connect("apex.db") as db:\n    db.row_factory = sqlite3.Row\n    db.execute("""CREATE TABLE IF NOT EXISTS learners (\n        learner_id INTEGER PRIMARY KEY,\n        name TEXT NOT NULL,\n        xp INTEGER NOT NULL DEFAULT 0 CHECK (xp >= 0)\n    )""")\n    db.execute("INSERT INTO learners(name, xp) VALUES (?, ?)", ("Maya", 100))\n    rows = db.execute("SELECT name, xp FROM learners WHERE xp >= ?", (50,)).fetchall()`,
      [['connection','Database session and transaction owner'],['cursor','Statement execution and result state'],['parameter binding','Safe data substitution'],['commit','Make transaction durable'],['rollback','Undo current transaction'],['IntegrityError','Constraint violation exception']],
      ['Formatting values into SQL with f-strings','Leaving transaction boundaries accidental','Relying only on Python checks instead of database constraints'],
      'Build a small SQLite repository for courses with schema constraints, parameterized CRUD, a transaction, and integrity-error handling.',
      'What can a SQL parameter safely replace?',['A table name','A column keyword','A data value','An ORDER BY direction'],2,'Parameters bind values; identifiers and syntax require controlled query construction.'),

    L('http-apis','Applications','HTTP clients, APIs, and serialization','Intermediate','Call web services with timeouts, validation, status handling, and retry discipline.',
      ['Understand request method, URL, headers, body, and response status','Set connect/read timeouts','Validate response data before use','Retry only suitable idempotent operations'],[
        ['HTTP exchange','A client sends a method, URL, headers, and optional body. The response contains a status, headers, and bytes. JSON is a representation, not the protocol itself. Check status and content type and do not assume every error response has the success schema.'],
        ['Reliability','Always set timeouts. Retry transient failures with bounded attempts, exponential backoff, and jitter, but consider whether the operation is idempotent. Repeating a POST that creates a record may duplicate work unless the API supports idempotency keys.'],
        ['Validation and security','Treat remote data as untrusted: validate required keys, types, ranges, and sizes. Keep credentials outside source code, send them only to expected HTTPS origins, redact them from logs, and follow pagination and rate-limit signals.']],
      `import requests\n\nresponse = requests.get(\n    "https://api.example.com/topics",\n    params={"course": "python"},\n    headers={"Accept": "application/json"},\n    timeout=(3.05, 10),\n)\nresponse.raise_for_status()\ndata = response.json()\nif not isinstance(data, list):\n    raise ValueError("expected a list of topics")`,
      [['method','Requested operation'],['status code','Response outcome class'],['header','Request or response metadata'],['timeout','Bound on waiting'],['idempotent','Repeat has same intended effect'],['pagination','Result split across requests']],
      ['Making requests with no timeout','Retrying every failed POST automatically','Trusting JSON shape because parsing succeeded'],
      'Write an API client function with explicit timeout, status handling, schema checks, pagination, and safe retry rules.',
      'Why is a parsed JSON response still untrusted?',['JSON cannot contain strings','Shape and values may violate expectations','HTTPS validates every field','Parsing executes the schema'],1,'Parsing proves valid JSON syntax, not application correctness or safety.'),

    L('security-quality','Quality','Security, style, performance, and packaging','Advanced','Finish projects with safe boundaries, readable conventions, measured optimization, and distributable structure.',
      ['Keep secrets out of code and logs','Follow PEP 8 and automated formatting','Profile before optimizing','Package applications with clear metadata and entry points'],[
        ['Security fundamentals','Validate untrusted input, parameterize SQL, avoid shell=True with user text, constrain filesystem paths, deserialize only safe formats, pin and review dependencies, and store secrets in environment or a secrets manager. Authorization must be checked at the operation, not inferred from UI state.'],
        ['Quality and performance','PEP 8 provides naming and layout conventions; formatters and linters automate consistency. Prefer clear algorithms and data structures. Measure with timeit, cProfile, or focused production metrics before optimizing. Reduce I/O and algorithmic complexity before micro-optimizing syntax.'],
        ['Packaging and delivery','pyproject.toml records build system, project metadata, dependencies, optional groups, and scripts. A src layout can prevent accidental imports from the working directory. Build wheels and source distributions, test installation in a clean environment, and publish only intended files.']],
      `[project]\nname = "apex-progress"\nversion = "1.0.0"\nrequires-python = ">=3.11"\ndependencies = []\n\n[project.scripts]\napex-progress = "apex_progress.cli:main"\n\n# In Python:\n# def main() -> int:\n#     ...\n#     return 0`,
      [['PEP 8','Python style guidance'],['formatter','Automatic source formatting'],['linter','Static quality checks'],['profiler','Measures runtime cost'],['wheel','Built Python distribution'],['entry point','Installed command mapping']],
      ['Embedding API keys in source','Optimizing unmeasured code while ignoring a poor algorithm','Publishing from a dirty or untested build environment'],
      'Turn a script into an installable command: add project metadata, safe configuration, formatting, linting, tests, profiling notes, and a clean-build check.',
      'What should happen before performance optimization?',['Rename variables','Measure the real bottleneck','Add threads everywhere','Disable tests'],1,'Measurement prevents effort on code that is not responsible for meaningful cost.')
  ];
})();
